import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parseUnifiedDiff } from '../dist/diff.js';

const SAMPLE = `diff --git a/src/app.js b/src/app.js
index 1111111..2222222 100644
--- a/src/app.js
+++ b/src/app.js
@@ -1,4 +1,6 @@
 const a = 1;
-const b = 2;
+const b = 3;
+const c = 4;
+// --- this added line starts with a plus and dashes are context-safe
 export default a;
diff --git a/assets/logo.png b/assets/logo.png
index 3333333..4444444 100644
Binary files a/assets/logo.png and b/assets/logo.png differ
diff --git a/gen/schema.js b/gen/schema.js
new file mode 100644
index 0000000..5555555
--- /dev/null
+++ b/gen/schema.js
@@ -0,0 +1,2 @@
+// @generated by schema-tool, do not edit
+export const schema = {};
`;

test('counts additions and deletions per file', () => {
  const parsed = parseUnifiedDiff(SAMPLE);
  assert.equal(parsed.files.length, 3);
  const app = parsed.files[0];
  assert.equal(app.path, 'src/app.js');
  assert.equal(app.additions, 3);
  assert.equal(app.deletions, 1);
  assert.equal(parsed.totalAdditions, 5);
  assert.equal(parsed.totalDeletions, 1);
});

test('detects binary files', () => {
  const parsed = parseUnifiedDiff(SAMPLE);
  const logo = parsed.files[1];
  assert.equal(logo.path, 'assets/logo.png');
  assert.equal(logo.binary, true);
  assert.equal(logo.additions, 0);
});

test('detects generated markers and new files', () => {
  const parsed = parseUnifiedDiff(SAMPLE);
  const gen = parsed.files[2];
  assert.equal(gen.created, true);
  assert.equal(gen.generatedMarker, true);
});

test('tracks the longest added line (minified detection input)', () => {
  const long = 'x'.repeat(900);
  const diff = [
    'diff --git a/dist/x.js b/dist/x.js',
    'index 1..2 100644',
    '--- a/dist/x.js',
    '+++ b/dist/x.js',
    '@@ -0,0 +1,1 @@',
    `+${long}`,
    '',
  ].join('\n');
  const parsed = parseUnifiedDiff(diff);
  assert.equal(parsed.files[0].maxAddedLineLength, 900);
});

test('handles renames', () => {
  const diff = [
    'diff --git a/old/name.js b/new/name.js',
    'similarity index 96%',
    'rename from old/name.js',
    'rename to new/name.js',
    '',
  ].join('\n');
  const parsed = parseUnifiedDiff(diff);
  assert.equal(parsed.files[0].renamed, true);
  assert.equal(parsed.files[0].path, 'new/name.js');
  assert.equal(parsed.files[0].oldPath, 'old/name.js');
});

test('empty input yields an empty parse, not an error', () => {
  const parsed = parseUnifiedDiff('');
  assert.deepEqual(parsed.files, []);
  assert.equal(parsed.totalAdditions, 0);
});
