import type { DiffFile, ParsedDiff } from './types.js';

const GENERATED_MARKER =
  /@generated|code generated by|do not edit|auto-?generated|automatically generated/i;

function stripPrefix(p: string): string {
  if (p.startsWith('a/') || p.startsWith('b/')) return p.slice(2);
  return p;
}

function newFile(path: string, oldPath: string): DiffFile {
  return {
    path,
    oldPath,
    additions: 0,
    deletions: 0,
    binary: false,
    renamed: false,
    created: false,
    removed: false,
    maxAddedLineLength: 0,
    generatedMarker: false,
  };
}

/**
 * A small, dependency-free unified diff parser. It is intentionally tolerant:
 * anything it cannot interpret is skipped rather than raising an error,
 * because GitHub truncates very large diffs and real-world diffs are messy.
 */
export function parseUnifiedDiff(text: string): ParsedDiff {
  const files: DiffFile[] = [];
  let current: DiffFile | null = null;
  let inHunk = false;

  for (const line of text.split(/\r?\n/)) {
    if (line.startsWith('diff --git ')) {
      const m = /^diff --git a\/(.+?) b\/(.+)$/.exec(line);
      const oldPath = m ? m[1] : line.slice('diff --git '.length);
      const path = m ? m[2] : oldPath;
      current = newFile(path, oldPath);
      files.push(current);
      inHunk = false;
      continue;
    }
    if (!current) continue;

    if (!inHunk) {
      if (line.startsWith('Binary files ') || line.startsWith('GIT binary patch')) {
        current.binary = true;
        continue;
      }
      if (line.startsWith('new file mode')) {
        current.created = true;
        continue;
      }
      if (line.startsWith('deleted file mode')) {
        current.removed = true;
        continue;
      }
      if (line.startsWith('rename from ')) {
        current.renamed = true;
        current.oldPath = line.slice('rename from '.length);
        continue;
      }
      if (line.startsWith('rename to ')) {
        current.renamed = true;
        current.path = line.slice('rename to '.length);
        continue;
      }
      if (line.startsWith('--- ')) {
        const p = line.slice(4).trim();
        if (p !== '/dev/null') current.oldPath = stripPrefix(p);
        continue;
      }
      if (line.startsWith('+++ ')) {
        const p = line.slice(4).trim();
        if (p !== '/dev/null') current.path = stripPrefix(p);
        continue;
      }
      if (line.startsWith('@@')) {
        inHunk = true;
      }
      continue;
    }

    // Inside a hunk. Subsequent hunk headers keep us in "hunk mode".
    if (line.startsWith('@@')) continue;
    if (line.startsWith('+')) {
      current.additions += 1;
      const content = line.slice(1);
      if (content.length > current.maxAddedLineLength) {
        current.maxAddedLineLength = content.length;
      }
      if (!current.generatedMarker && GENERATED_MARKER.test(content)) {
        current.generatedMarker = true;
      }
    } else if (line.startsWith('-')) {
      current.deletions += 1;
    }
    // Context lines, "\ No newline at end of file", etc. are ignored.
  }

  return {
    files,
    totalAdditions: files.reduce((n, f) => n + f.additions, 0),
    totalDeletions: files.reduce((n, f) => n + f.deletions, 0),
  };
}
